'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, MessageSquare, Paperclip, RefreshCw, Search, Send, Smartphone, X } from 'lucide-react';
import { useCommercial } from '@/components/commercial/CommercialShell';

type Conversation = { id: string; telefone: string; nome_contato: string | null; status: string | null; ultima_mensagem_at: string | null; commercial_lead: { nome: string; status: string } };
type Message = { id: string; direction: 'inbound' | 'outbound'; mensagem: string; created_at: string };
type WhatsappState = { configured: boolean; connected: boolean; state: 'open' | 'connecting' | 'close'; targetProfile?: { id?: string; nome?: string | null } | null };
const time = (value?: string | null) => value ? new Date(value).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '';
const normalizePhone = (value: string) => value.replace(/\D/g, '').replace(/^55/, '');

export default function CommercialInboxPage() {
  const { api, role } = useCommercial();
  const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<Conversation | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [search, setSearch] = useState(''); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [notice, setNotice] = useState(''); const [qr, setQr] = useState<string | null>(null); const [whatsapp, setWhatsapp] = useState<WhatsappState>({ configured: false, connected: false, state: 'close' });
  const loadWhatsapp = useCallback(async () => { try { const payload = await api('/api/comercial/inbox/whatsapp'); setWhatsapp(payload); } catch (error) { setNotice(error instanceof Error ? error.message : 'Nao foi possivel consultar o WhatsApp.'); } }, [api]);
  const load = useCallback(async () => { setLoading(true); try { const payload = await api('/api/comercial/inbox'); const next = payload.conversations || []; setConversations(next); const phone = new URLSearchParams(window.location.search).get('telefone'); if (phone) setSelected(next.find((item: Conversation) => normalizePhone(item.telefone) === normalizePhone(phone)) || null); } catch (error) { setNotice(error instanceof Error ? error.message : 'Nao foi possivel carregar o Inbox.'); } finally { setLoading(false); } }, [api]);
  const loadMessages = useCallback(async (conversation: Conversation) => { try { const payload = await api(`/api/inbox/messages?conversation_id=${conversation.id}`); setMessages(payload.messages || []); } catch (error) { setNotice(error instanceof Error ? error.message : 'Nao foi possivel carregar as mensagens.'); } }, [api]);
  useEffect(() => { void load(); void loadWhatsapp(); const timer = window.setInterval(() => void loadWhatsapp(), 15000); return () => window.clearInterval(timer); }, [load, loadWhatsapp]); useEffect(() => { if (selected) void loadMessages(selected); }, [loadMessages, selected]);
  const filtered = useMemo(() => conversations.filter((item) => `${item.nome_contato || ''} ${item.telefone} ${item.commercial_lead.nome}`.toLowerCase().includes(search.toLowerCase())), [conversations, search]);
  async function connectWhatsapp() { try { const payload = await api('/api/comercial/inbox/whatsapp', { method: 'POST', body: JSON.stringify({ accepted_terms: true, terms_version: 'commercial-inbox-v1' }) }); setQr(payload.qrcode || null); setWhatsapp((current) => ({ ...current, configured: true, state: 'connecting', connected: false })); setNotice(payload.qrcode ? 'Escaneie o QR Code com o WhatsApp.' : 'Conexao iniciada.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Falha ao conectar WhatsApp.'); } }
  async function sendMessage(event: React.FormEvent) { event.preventDefault(); if (!selected || !draft.trim()) return; setSending(true); try { await api('/api/inbox/messages', { method: 'POST', body: JSON.stringify({ conversation_id: selected.id, mensagem: draft.trim() }) }); setDraft(''); await loadMessages(selected); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : 'Nao foi possivel enviar.'); } finally { setSending(false); } }
  const connectionLabel = !whatsapp.configured ? 'WhatsApp não configurado' : whatsapp.state === 'open' ? 'WhatsApp conectado' : whatsapp.state === 'connecting' ? 'WhatsApp aguardando conexão' : 'WhatsApp desconectado';
  return <div className="kh-commercial-inbox"><header className="kh-page-head"><div><div className="kh-eyebrow">Atendimento comercial</div><h1>Inbox</h1><p>{role === 'sdr' ? 'Aqui aparecem somente as conversas dos leads atribuídos a você.' : 'Acompanhe as conversas do time e os atendimentos dos SDRs.'}</p></div><div className="kh-actions"><button className="kh-button" onClick={() => { void load(); void loadWhatsapp(); }}><RefreshCw size={15} className={loading ? 'kh-spin' : ''} /> Atualizar</button><button className="kh-button primary" onClick={() => void connectWhatsapp()} disabled={whatsapp.state === 'open'}><Smartphone size={15} /> {whatsapp.state === 'open' ? 'WhatsApp conectado' : 'Conectar meu WhatsApp'}</button></div></header>
    <div className={`kh-whatsapp-status ${whatsapp.state}`}><span className="kh-whatsapp-status-dot" /> <strong>{connectionLabel}</strong><span>{whatsapp.state === 'open' ? `${whatsapp.targetProfile?.nome || 'Seu usuário'} está pronto para enviar e receber mensagens.` : whatsapp.state === 'connecting' ? 'Leia o QR Code para ativar seu atendimento.' : 'Conecte o WhatsApp deste usuário para atender seus leads.'}</span>{whatsapp.state === 'open' && <CheckCircle2 size={16} />}</div>
    {notice && <div className="kh-inline-error">{notice}<button aria-label="Fechar aviso" onClick={() => setNotice('')}><X size={14} /></button></div>}
    {qr && <div className="kh-panel kh-whatsapp-qr"><div><strong>Conecte o WhatsApp</strong><p>Abra o WhatsApp no celular e escaneie o codigo.</p></div><img src={qr.startsWith('data:') ? qr : `data:image/png;base64,${qr}`} alt="QR Code para conectar WhatsApp" /><button className="kh-icon-button" onClick={() => setQr(null)} aria-label="Fechar QR Code"><X size={16} /></button></div>}
    <section className="kh-inbox-layout"><aside className="kh-panel kh-conversation-list"><div className="kh-inbox-list-head"><strong>Conversas</strong><span>{filtered.length}</span></div><label className="kh-inbox-search"><Search size={15} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar nome ou telefone..." /></label><div className="kh-conversations">{filtered.map((conversation) => <button key={conversation.id} className={selected?.id === conversation.id ? 'active' : ''} onClick={() => setSelected(conversation)}><span className="kh-avatar">{(conversation.nome_contato || conversation.commercial_lead.nome).split(' ').slice(0, 2).map((part) => part[0]).join('').toUpperCase()}</span><span className="kh-conversation-copy"><strong>{conversation.nome_contato || conversation.commercial_lead.nome}</strong><small>{conversation.commercial_lead.nome} · {conversation.commercial_lead.status}</small></span><time>{time(conversation.ultima_mensagem_at)}</time></button>)}{!filtered.length && <div className="kh-inbox-empty">Nenhuma conversa encontrada.</div>}</div></aside><main className="kh-panel kh-chat"><div className="kh-chat-head">{selected ? <><div className="kh-avatar">{(selected.nome_contato || selected.commercial_lead.nome).slice(0, 2).toUpperCase()}</div><div><strong>{selected.nome_contato || selected.commercial_lead.nome}</strong><span>{selected.telefone} · {selected.commercial_lead.status}</span></div></> : <><MessageSquare size={22} /><div><strong>Selecione uma conversa</strong><span>O admin visualiza SDR e Closer no mesmo Inbox.</span></div></>}</div><div className="kh-chat-messages">{messages.map((message) => <div key={message.id} className={`kh-chat-bubble ${message.direction === 'outbound' ? 'outbound' : 'inbound'}`}><p>{message.mensagem}</p><time>{time(message.created_at)}</time></div>)}{selected && !messages.length && <div className="kh-inbox-empty">Nenhuma mensagem registrada.</div>}</div><form className="kh-chat-compose" onSubmit={sendMessage}><Paperclip size={17} /><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={selected ? 'Digite uma mensagem...' : 'Selecione uma conversa'} disabled={!selected || sending} /><button className="kh-icon-button" disabled={!selected || sending || !draft.trim()} aria-label="Enviar mensagem"><Send size={16} /></button></form></main></section><small className="kh-inbox-role">Acesso atual: {role === 'coordenador' ? 'coordenador' : role === 'sdr' ? 'SDR' : 'Closer'}</small></div>;
}
